/* krpano 1.17.pr2 scrollarea plugin (build 2014-01-10) */
var krpanoplugin=function(){function E(a){return"boolean"==typeof a?a:0<="yesontrue1".indexOf(String(a).toLowerCase())}function P(a){if(a&&j){var g=j.timertick,b=0;0==F&&(F=g);var e=g-F|0;F=g;"wheel"==a.type?b=a.deltaY:"mousewheel"==a.type?b=-a.wheelDelta:"DOMMouseScroll"==a.type&&(b=a.detail);b=-b;500<e?G=1==a.deltaMode||0==b%20?0:1:66>e&&(0==G&&0!=b%40&&6<Math.abs(b))&&(G=1);a.preventDefault();a.stopPropagation();Q&&0!=b&&(0==G?b=0>b?-5:5:(b/=20,-10>b?b=-10:10<b&&(b=10)),1==f?H(b*v,0):2==f?H(0,
b*t):3==f&&H(0,b*t))}}function s(a,g,b,e,d){var c=null;d=(!0===d?"remove":"add")+"EventListener";var f=I.browser.events;if(f.touch&&("down"==g?c=f.touchstart:"move"==g?c=f.touchmove:"up"==g&&(c=f.touchend),I.ie&&!1==f.mouse&&("over"==g?c=f.pointerover?f.pointerover:"MSPointerOver":"out"==g&&(c=f.pointerout?f.pointerout:"MSPointerOut")),c))a[d](c,b,e);if(f.mouse&&("down"==g?c="mousedown":"move"==g?c="mousemove":"up"==g?c="mouseup":"over"==g?c="mouseover":"out"==g&&(c="mouseout"),c))a[d](c,b,e)}function R(){if(b){var a=
b.sprite.parentNode;if(a&&(a=a.kobject))a.maskchildren=!0,a.poschanged&&a.updatepluginpos(),S=a,n=a.pixelwidth,p=a.pixelheight,isNaN(n)&&(n=0),isNaN(p)&&(p=0),C=0<n||0<p}}function J(a){a=void 0===a?!1:a;1==(f&1)?b.x!=d&&(b.x=d,a=!0):d=0;2==(f&2)?b.y!=c&&(b.y=c,a=!0):c=0;if(a&&b&&b.onscroll){if(C){a=n-w;var g=p-x,m=d,e=c;isNaN(m)&&(m=0);isNaN(e)&&(e=0);m+=a*q;e+=g*r;b.woverflow=-a;b.hoverflow=-g;b.loverflow=Math.round((-m+A*a)*v);b.roverflow=Math.round((+m-(1-A)*a)*v);b.toverflow=Math.round((-e+B*
g)*t);b.boverflow=Math.round((+e-(1-B)*g)*t)}j.call(b.onscroll,b)}}function X(a){for(;0<u.length&&!(100>=a-u[0].time);)u.shift()}function K(){R();var a=String(b.align).toLowerCase();if(""==a||"null"==a)a="lefttop";t=v=1;r=q=0.5;B=A=0;0<=a.indexOf("left")&&(q=A=0,v=1);0<=a.indexOf("top")&&(r=B=0,t=1);0<=a.indexOf("right")&&(A=1,q=0,v=-1);0<=a.indexOf("bottom")&&(B=1,r=0,t=-1)}function Y(a){K();u=[];if(!1==T)y=!1;else{s(window,"up",Z,!0);s(window,"move",$,!0);var g=j.stagescale,b=a.changedTouches&&
0<a.changedTouches.length?a.changedTouches[0]:a;a=b.pageX/g;g=b.pageY/g;y=!1;L=a;M=g;return!1}}function aa(a){if((void 0===a.pointerType||4==a.pointerType||"mouse"==a.pointerType)&&U)if(K(),!1!=C&&(a=p-x,0>n-w||0>a))D=!0,s(b.sprite,"move",ba,!0),s(b.sprite,"out",ca,!0)}function ba(){if(D&&!1==y&&S){var a=S.getmouse();N(a.x/n*b.pixelwidth,a.y/p*b.pixelheight,!0)}}function ca(){s(b.sprite,"move",ba,!0,!0);s(b.sprite,"out",ca,!0,!0);D=!1}function $(a){var g=j.stagescale,m=a.changedTouches&&0<a.changedTouches.length?
a.changedTouches[0]:a,e=m.pageX/g,g=m.pageY/g;if(!1==y&&(f&1&&5<Math.abs(e-L)||f&2&&5<Math.abs(g-M)))z&&(h=k=0,z=!1),null!=l&&(clearInterval(l),l=null),y=!0,D=!1,L=e,M=g,d=Number(b.x),c=Number(b.y),isNaN(V)&&(d=0),isNaN(W)&&(c=0),V=d,W=c;y&&(a=a.timeStamp,X(a),u.push({time:a,x:e,y:g}),d=V+(e-L)*v,c=W+(g-M)*t,e=-(w-n),a=-(x-p),d+=e*q,c+=a*r,d=0<e?d-(d-e*q)/2:d-(0<d?d:d<e?d-e:0)/2,c=0<a?c-(c-a*r)/2:c-(0<c?c:c<a?c-a:0)/2,d-=e*q,c-=a*r,J());return!1}function Z(a){s(window,"up",Z,!0,!0);s(window,"move",
$,!0,!0);if(y){X(a.timeStamp);if(1<u.length){a=u[0];var g=u[u.length-1],b=g.y-a.y,e=(g.time-a.time)/15;k=(g.x-a.x)/e*v;h=b/e*t}else h=k=0;l=setInterval(O,1E3/60);y=!1}}function ia(){setTimeout(function(){R();J(!0);null==l&&(l=setInterval(O,1E3/60))},100)}function O(){d+=k;c+=h;k*=da;h*=da;var a=0,b=0,m=-(w-n),e=-(x-p);d+=m*q;c+=e*r;0<m?a=d-m*q:z?a=d-ea:d<m?a=d-m:0<d&&(a=d);0.1>a*a&&(a=0);0<e?b=c-e*r:z?b=c-fa:c<e?b=c-e:0<c&&(b=c);0.1>b*b&&(b=0);d-=m*q;c-=e*r;0==(f&1)&&(k=a=0);0==(f&2)&&(h=b=0);0!=
a&&(a*=-1,k=0>=a*k?k+a*ga:a*ha);0!=b&&(b*=-1,h=0>=b*h?h+b*ga:b*ha);0==a&&(0==b&&0.05>Math.sqrt(k*k+h*h))&&(z=!1,h=k=0,clearInterval(l),l=null);J()}function N(a,b,f){K();if(!1==C)setTimeout(function(){N(a,b,f)},10);else{a=Number(a);isNaN(a)&&(a=0);b=Number(b);isNaN(b)&&(b=0);var e=n-w,h=p-x;a=A*w+a*v;b=B*x+b*t;a*=-1;b*=-1;a+=n/2;0<a&&(a=0);a<e&&(a=e);b+=p/2;0<b&&(b=0);b<h&&(b=h);!0===f?(z=!0,ea=a,fa=b,null==l&&(l=setInterval(O,1E3/60))):(e=-(w-n),h=-(x-p),a=0>e?a-e*q:0,b=0>h?b-h*r:0,d=a,c=b,J())}}
function ja(a,b){N(a,b,!0)}function ka(){null!=l&&(clearInterval(l),l=null);D=y=!1;u=[];h=k=0;z=!1}function H(a,b){z=!1;a=Number(a);isNaN(a)&&(a=0);b=Number(b);isNaN(b)&&(b=0);K();if(!1!=C){var f=n-w,e=p-x,j=!1;0>f&&(d+=f*q,0<a&&0>d?(j=!0,k+=a):0>a&&d>f&&(j=!0,k+=a),d-=f*q);0>e&&(c+=e*r,0<b&&0>c?(j=!0,h+=b):0>b&&c>e&&(j=!0,h+=b),c-=e*r);j&&null==l&&(l=setInterval(O,1E3/60))}}var j=null,b=null,I=null,f=3,w=0,x=0,C=!1,S=null,n=0,p=0,z=!1,ea=0,fa=0,v=1,t=1,q=0,r=0,A=0,B=0,da=0.95,ga=0.08,ha=0.15,T=!0,
Q=!0,y=!1,L=0,M=0,d=0,c=0,V=0,W=0,l=null,u=[],k=0,h=0,D=!1,U=!1;this.registerplugin=function(a,c,d){j=a;b=d;"1.16">j.version?(j.trace(3,"Scrollarea Plugin - too old krpano version (min. version 1.16)"),b=j=null):(I=j.device,b.registerattribute("direction","all",function(a){a=String(a).toLowerCase();f=0;f|=1*(0<=a.indexOf("h"));f|=2*(0<=a.indexOf("v"));f|=3*(0<=a.indexOf("all"))},function(){return 3==(f&3)?"all":1==(f&1)?"h":"v"}),b.registerattribute("onscroll",null),b.registerattribute("woverflow",
0),b.registerattribute("hoverflow",0),b.registerattribute("loverflow",0),b.registerattribute("roverflow",0),b.registerattribute("toverflow",0),b.registerattribute("boverflow",0),b.registerattribute("draggable",!0,function(a){T=E(a)},function(){return T}),b.registerattribute("mwheel",!0,function(a){Q=E(a)},function(){return Q}),b.registerattribute("onhover_autoscrolling",!1,function(a){U=E(a)},function(){return U}),b.registerattribute("csshardwareacceleration","auto"),b.setcenter=N,b.scrolltocenter=
ja,b.stopscrolling=ka,b.scrollby=H,!0==E(b.csshardwareacceleration)&&(b.sprite.style[I.browser.css.transform+"Style"]="preserve-3d"),b.sprite.addEventListener("DOMMouseScroll",P,!0),b.sprite.addEventListener("mousewheel",P,!0),b.sprite.addEventListener("wheel",P,!0),s(b.sprite,"down",Y,!0),s(b.sprite,"over",aa,!0),j.set("events["+b.name+"_scrollarea].keep",!0),j.set("events["+b.name+"_scrollarea].onresize",ia))};var F=0,G=0;this.onresize=function(a,b){if(!j)return!1;w=a;x=b;R();return!1};this.unloadplugin=
function(){j&&b&&(j.set("events["+b.name+"_scrollarea].name",null),null!=l&&(clearInterval(l),l=null),s(b.sprite,"down",Y,!0,!0),s(b.sprite,"over",aa,!0,!0));j=b=null}};
